"""persist validated historical bars

Revision ID: 2beac83591a7
Revises: a05b8c67dff0
Create Date: 2026-08-19 22:44:27.371172
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2beac83591a7'  # pragma: allowlist secret -- Alembic revision identifier
down_revision: Union[str, None] = 'a05b8c67dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('data_quality', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('manifest_checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'provider', 'interval', 'timestamp', name='uq_historical_bar')
    )
    op.create_index('ix_historical_bar_lookup', 'historical_bars', ['instrument_id', 'interval', 'timestamp'], unique=False)
    op.create_index(op.f('ix_historical_bars_instrument_id'), 'historical_bars', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_historical_bars_interval'), 'historical_bars', ['interval'], unique=False)
    op.create_index(op.f('ix_historical_bars_manifest_checksum'), 'historical_bars', ['manifest_checksum'], unique=False)
    op.create_index(op.f('ix_historical_bars_provider'), 'historical_bars', ['provider'], unique=False)
    op.create_index(op.f('ix_historical_bars_timestamp'), 'historical_bars', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_bars_timestamp'), table_name='historical_bars')
    op.drop_index(op.f('ix_historical_bars_provider'), table_name='historical_bars')
    op.drop_index(op.f('ix_historical_bars_manifest_checksum'), table_name='historical_bars')
    op.drop_index(op.f('ix_historical_bars_interval'), table_name='historical_bars')
    op.drop_index(op.f('ix_historical_bars_instrument_id'), table_name='historical_bars')
    op.drop_index('ix_historical_bar_lookup', table_name='historical_bars')
    op.drop_table('historical_bars')
    # ### end Alembic commands ###
