"""initial trading schema

Revision ID: a05b8c67dff0
Revises: 
Create Date: 2026-08-19 22:42:08.443230
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a05b8c67dff0'  # pragma: allowlist secret -- Alembic revision identifier
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_category'), 'audit_events', ['category'], unique=False)
    op.create_index(op.f('ix_audit_events_severity'), 'audit_events', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('data_manifest_ids', sa.JSON(), nullable=False),
    sa.Column('reproducibility_hash', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_name'), 'backtests', ['name'], unique=False)
    op.create_index(op.f('ix_backtests_reproducibility_hash'), 'backtests', ['reproducibility_hash'], unique=False)
    op.create_index(op.f('ix_backtests_status'), 'backtests', ['status'], unique=False)
    op.create_index(op.f('ix_backtests_strategy'), 'backtests', ['strategy'], unique=False)
    op.create_table('data_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('missing_intervals', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('usage_note', sa.Text(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('cache_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_manifests_checksum'), 'data_manifests', ['checksum'], unique=False)
    op.create_index(op.f('ix_data_manifests_instrument'), 'data_manifests', ['instrument'], unique=False)
    op.create_index(op.f('ix_data_manifests_provider'), 'data_manifests', ['provider'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=True),
    sa.Column('ig_epic', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_asset_class'), 'instruments', ['asset_class'], unique=False)
    op.create_index(op.f('ix_instruments_ig_epic'), 'instruments', ['ig_epic'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('managed_capital_ledgers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_capital_ledgers_portfolio_id'), 'managed_capital_ledgers', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_managed_capital_ledgers_timestamp'), 'managed_capital_ledgers', ['timestamp'], unique=False)
    op.create_table('system_state',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('backtest_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('expected_growth_score', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('candidate', sa.JSON(), nullable=False),
    sa.Column('challenge', sa.JSON(), nullable=False),
    sa.Column('risk_decision', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_approved'), 'opportunities', ['approved'], unique=False)
    op.create_index(op.f('ix_opportunities_backtest_id'), 'opportunities', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_opportunities_expected_growth_score'), 'opportunities', ['expected_growth_score'], unique=False)
    op.create_index(op.f('ix_opportunities_instrument'), 'opportunities', ['instrument'], unique=False)
    op.create_index(op.f('ix_opportunities_strategy'), 'opportunities', ['strategy'], unique=False)
    op.create_index(op.f('ix_opportunities_timestamp'), 'opportunities', ['timestamp'], unique=False)
    op.create_index('ix_opportunity_rank', 'opportunities', ['timestamp', 'expected_growth_score'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('backtest_id', sa.String(length=36), nullable=True),
    sa.Column('order_intent_id', sa.String(length=36), nullable=False),
    sa.Column('instrument', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('equity_before', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('equity_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_instrument_time', 'trades', ['instrument', 'opened_at'], unique=False)
    op.create_index(op.f('ix_trades_backtest_id'), 'trades', ['backtest_id'], unique=False)
    op.create_index(op.f('ix_trades_closed_at'), 'trades', ['closed_at'], unique=False)
    op.create_index(op.f('ix_trades_instrument'), 'trades', ['instrument'], unique=False)
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trades_order_intent_id'), 'trades', ['order_intent_id'], unique=True)
    op.create_index(op.f('ix_trades_strategy'), 'trades', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_intent_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument'), table_name='trades')
    op.drop_index(op.f('ix_trades_closed_at'), table_name='trades')
    op.drop_index(op.f('ix_trades_backtest_id'), table_name='trades')
    op.drop_index('ix_trade_instrument_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_opportunity_rank', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_timestamp'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_strategy'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_instrument'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_expected_growth_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_backtest_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_approved'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_managed_capital_ledgers_timestamp'), table_name='managed_capital_ledgers')
    op.drop_index(op.f('ix_managed_capital_ledgers_portfolio_id'), table_name='managed_capital_ledgers')
    op.drop_table('managed_capital_ledgers')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_ig_epic'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_asset_class'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_data_manifests_provider'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_instrument'), table_name='data_manifests')
    op.drop_index(op.f('ix_data_manifests_checksum'), table_name='data_manifests')
    op.drop_table('data_manifests')
    op.drop_index(op.f('ix_backtests_strategy'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_status'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_reproducibility_hash'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_name'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_severity'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_category'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
